### ISSUE TITLE
Parsing IPN Messages is not parsing AuthorizationDetails correctly

### ISSUE THREAD

**Issue by GRSwaminathan** [amzn/amazon-pay-sdk-java#17]
Trying to parse the IPN Message using NotificationFactory.parseNotification(headerMap, bodyJson); results in a empty AuthorizationDetails. Debugging into the issue i found that the unmarshal of "NotificationData"  is not successful and throws a Runtime Exception.

`Exception in thread "main" java.lang.RuntimeException: unexpected element (uri:"", local:"AmazonAuthorizationId"). Expected elements are <{http://mws.amazonservices.com/schema/OffAmazonPayments/2013-01-01}AuthorizationStatus>,<{http://mws.amazonservices.com/schema/OffAmazonPayments/2013-01-01}AuthorizationAmount>,<{http://mws.amazonservices.com/schema/OffAmazonPayments/2013-01-01}AddressVerificationCode>,<{http://mws.amazonservices.com/schema/OffAmazonPayments/2013-01-01}SoftDecline>,<{http://mws.amazonservices.com/schema/OffAmazonPayments/2013-01-01}AmazonAuthorizationId>,<{http://mws.amazonservices.com/schema/OffAmazonPayments/2013-01-01}CreationTimestamp>,<{http://mws.amazonservices.com/schema/OffAmazonPayments/2013-01-01}ExpirationTimestamp>,<{http://mws.amazonservices.com/schema/OffAmazonPayments/2013-01-01}CaptureNow>,<{http://mws.amazonservices.com/schema/OffAmazonPayments/2013-01-01}OrderItemCategories>,<{http://mws.amazonservices.com/schema/OffAmazonPayments/2013-01-01}AuthorizationFee>,<{http://mws.amazonservices.com/schema/OffAmazonPayments/2013-01-01}SellerAuthorizationNote>,<{http://mws.amazonservices.com/schema/OffAmazonPayments/2013-01-01}AuthorizationReferenceId>,<{http://mws.amazonservices.com/schema/OffAmazonPayments/2013-01-01}AuthorizationBillingAddress>,<{http://mws.amazonservices.com/schema/OffAmazonPayments/2013-01-01}IdList>,<{http://mws.amazonservices.com/schema/OffAmazonPayments/2013-01-01}SoftDescriptor>,<{http://mws.amazonservices.com/schema/OffAmazonPayments/2013-01-01}CapturedAmount>`

Also, noticed that the IPN Test cases does not check if the message is parsed correctly. So this will not be identified in JUnit tests.

I'm Attaching the json that i used and the java file that can be used for checking.
NOTE: Rename AuthorizationNotification3.txt -> AuthorizationNotification3.json and Test.txt -> Test.json

[AuthorizationNotification3.txt](https://github.com/amzn/amazon-pay-sdk-java/files/1025673/AuthorizationNotification3.txt)
[Test.txt](https://github.com/amzn/amazon-pay-sdk-java/files/1025672/Test.txt)

**Comment by bjguillot** [comment]
Can you confirm what version of the Java SDK were you testing with?

**Comment by GRSwaminathan** [comment]
I'm using 64-bit Java 8 (build 1.8.0_111-b14)

**Comment by bjguillot** [comment]
I'm sorry. Let me clarify the question: What version of the Amazon Pay Java SDK are you using?  Is it  the latest 3.0.2 version available from the releases page or an earlier version?

https://github.com/amzn/amazon-pay-sdk-java/releases

There was an IPN fix for the AuthorizationNotification back in the 2.2.1 version in January.  I just want to be sure you are using at least version 2.2.1 or higher.

**Comment by GRSwaminathan** [comment]
I am using 3.0.1, but tried using 3.0.2 as well but with same results.

**Comment by bjguillot** [comment]
OK, it looks like we have a dependency on two additional jar files: jaxb-core and jaxb-impl.  If a version of these jar files are not in your classpath, the situation you described will occur (i.e., no errors or exceptions displayed, but you get an empty AuthorizationDetails.)

I have attached a modified version of your test file, commenting out all your test processing, and it runs successfully from the command line with the following command:

java -cp lib/amazon-pay-3.0.2.jar:lib/commons-logging-1.2.jar:lib/gson-2.2.2.jar:lib/jaxb-core-2.2.11.jar:lib/jaxb-impl-2.2.11.jar:. IpnTest

[IpnTest.java.txt](https://github.com/amzn/amazon-pay-sdk-java/files/1027472/IpnTest.java.txt)

**Comment by GRSwaminathan** [comment]
Great, that solves the issue. Thanks for the support.

**Comment by bjguillot** [comment]
OK, glad to hear adding the jars to the classpath solved the issue.

I'll be sure to update our README file and third party lib folder during our next Amazon Pay Java SDK update to describe the required jar files.

I apologize for the inconvenience this caused.
