### ISSUE TITLE
BillingAgreementNotification Message object have a property "EventType" and not being parsed as MessageMetaData

### ISSUE THREAD

**Issue by kansology** [amzn/amazon-pay-sdk-java#18]
EventType element of "Message" object is important to know what kind of Billing Notification came and use it accordingly.
Currently it is not part of "IPNMessageMetaData" object causing problem to parse manually rather than using the sdk.

**Comment by bjguillot** [comment]
kansology, thanks for the report.  I actually noticed this just the other day and the change to fix this is already queued up for the next Java SDK release (undergoing testing now).

**Comment by bjguillot** [comment]
This was fixed in version 3.1.0.
