### ISSUE TITLE
inconsistent release numbering

### ISSUE THREAD

**Issue by stefanofornari** [amzn/amazon-pay-sdk-java#20]
Hello,
I see here: https://github.com/amzn/amazon-pay-sdk-java/releases
that 3.3.0 has been released, but the source code (pom.xml is still 3.1.0 ...)

**Comment by bjguillot** [comment]
Thanks for bringing this to our attention.  We will fix this in the next release.

**Comment by bjguillot** [comment]
This was fixed in a prior release.
