### ISSUE TITLE
java.lang.NoSuchMethodError: in v3.3.0 (o v3.1.0) 

### ISSUE THREAD

**Issue by stefanofornari** [amzn/amazon-pay-sdk-java#21]
I am having trouble with the latest version of the SDK:

java.lang.NoSuchMethodError: com.amazon.pay.impl.Util.getServiceURLEndpoint(Lcom/amazon/pay/Config;)Ljava/lang/String;
	at com.amazon.pay.impl.PayClient.postRequest(PayClient.java:1182)
	at com.amazon.pay.impl.PayClient.sendRequest(PayClient.java:1154)
	at com.amazon.pay.impl.PayClient.setOrderReferenceDetails(PayClient.java:300)

**Comment by bjguillot** [comment]
I have not been able to replicate your issue with the amazon-pay-3.3.0.jar file included in the "releases" screen.  Can you provide some more context behind this such as a snippet of code showing you you are using the SetOrderReferenceDetails method?

**Comment by stefanofornari** [comment]
Sorry, my fault in my testing framework...
