### ISSUE TITLE
GetOrderReferenceDetails returns garbled Japanese text

### ISSUE THREAD

**Issue by rougou** [amzn/amazon-pay-sdk-java#24]
Hi, I have an application that uses the SDK to retrieve shipping address details from amazon.co.jp accounts.
Everything was working fine when launching from Eclipse, but text returned garbled on our development server.
I found the likely cause is that "UTF-8" is not specified when the InputStreamReader is created [here](https://github.com/amzn/amazon-pay-sdk-java/blob/549612ed848f7c150a6694cbbde714ee6e209cca/src/com/amazon/pay/impl/Util.java#L126-L130).

As a quick workaround we can specify `-Dfile.encoding=UTF-8` when launching the application to force UTF-8 to be used, but it would be preferable if you can fix the SDK to specify "UTF-8" (or the handy StandardCharsets.UTF_8 from JDK7+) directly in the code.

Thanks.

edit: Our development server itself is set to UTF-8, but the docker container the application is launched in apparently is not. Either way, it would be best if the SDK doesn't rely on environment settings.

**Comment by bjguillot** [comment]
Thank for you the bug report.  If we are able to confirm the issue, I'll work to get it scheduled for inclusion into our next SDK release.

**Comment by bjguillot** [comment]
We have implemented this change in:

https://github.com/amzn/amazon-pay-sdk-java/releases/tag/3.4.1
