### ISSUE TITLE
com.amazon.pay.parser.Parser uses to different methods to get a new XMLInputFactory instance

### ISSUE THREAD

**Issue by lansacoder** [amzn/amazon-pay-sdk-java#25]
generateErrorException(ResponseData rawResponse) uses this:

        final XMLInputFactory xmlInputFactory = XMLInputFactory.newFactory();

public static <T> T marshalXML(Class<T> clazz, ResponseData rawResponse) uses this:

    final XMLInputFactory xmlInputFactory = XMLInputFactory.newInstance();

For my environment, I changed them both to use newInstance(), as the jars that already in use on my site do not have the newFactory() method.  

I only reported this because it seems inconsistent.

BTW,  Thanks so much for all the work that has been put into this.

**Comment by bjguillot** [comment]
Thank you for bringing this to our attention.  We attempted to address this last year in version 3.0.1, but it looks like we missed one of the three spots in the code that newFactory was used.  I'll queue up this change for the next release.

**Comment by balibani** [comment]
Line 242 in Response.java should be updated  from  XMLInputFactory xmlInputFactory = XMLInputFactory.newFactory(); to  XMLInputFactory xmlInputFactory = XMLInputFactory.newInstance();

**Comment by bjguillot** [comment]
We have implemented this change in: 

https://github.com/amzn/amazon-pay-sdk-java/releases/tag/3.4.1
