### ISSUE TITLE
Latest version (3.4.0) not in maven central

### ISSUE THREAD

**Issue by rougou** [amzn/amazon-pay-sdk-java#26]
3.4.0 is not in maven central. Do you plan to add it?
https://mvnrepository.com/artifact/com.amazon.pay/amazon-pay-java-sdk

**Comment by bjguillot** [comment]
Thanks for the reminder.  Yes, stay tuned.

**Comment by sebastianreloaded** [comment]
hi,
just a friendly reminder: 3.4.0 is still not on maven central.

**Comment by bjguillot** [comment]
Version 3.4.0 is now posted to Maven Central: https://search.maven.org/search?q=com.amazon.pay

I apologize for the delay in getting this posted.  We will be quicker next time.
