### ISSUE TITLE
Not supported for All currency code

### ISSUE THREAD

**Issue by Vibzzz** [amzn/amazon-pay-sdk-java#29]

**Comment by bjguillot** [comment]
Can you provide more details about your issue?

The Java SDK supports all currency modes supported by Amazon Pay.  US region supports only USD.  JP region supports only JPY.  EU and UK regions support EUR and GBP respectively.

Specific additional currencies can be supported in the EU and UK regions if the multi-currency feature is enabled on the merchant account.
