### ISSUE TITLE
xxe

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [amzn/amazon-pay-sdk-java#30]
When parsing the xml string (parameter data), the xml external entity is not disabled, and the attacker may control the data to perform the xml external entity injection attack.

![图片](https://user-images.githubusercontent.com/39950310/57598865-68c0a080-7587-11e9-8ef9-8a91f2653303.png)

**Comment by bjguillot** [comment]
Thank you for bringing this to our attention.  We are investigating.

**Comment by bjguillot** [comment]
Thanks.  This was resolved back in Version 3.5.1 - May 2019.
