### ISSUE TITLE
Amazon pay sdk crashes in android app

### ISSUE THREAD

**Issue by suyashtravel** [amzn/amazon-pay-sdk-java#31]
Hi, I am using AmazonPay sdk for the payment in my app but sometimes i am getting crashes 
"SourceFile line 12 in amazonpay.silentpay.n.a". I don't know why it is happening or how can i fix it.

**Comment by bjguillot** [comment]
I don't recognize the package name amazonpay.silentpay.n.a.  Can you provide a fuller stack trace with more details?

Are you trying to use this in North America, Europe, Japan, or India?

**Comment by suyashtravel** [comment]
Providing the stack trace for error
```

SourceFile  line  12 in amazonpay.silentpay.n.a()
--
amazonpa...entpay.n | SourceFile  line  18 in amazonpay.silentpay.n.a()
amazonpa...mazonPay | SourceFile  line  239 in amazonpay.silentpay.AmazonPay.a()
amazonpa...mazonPay | SourceFile  line  233 in amazonpay.silentpay.AmazonPay.getChargeStatus()
com..Fragment | AmazonPayFragment.java  line  367 in com.common.checkout.payment.amazonpay.AmazonPayFragment.startAmazonPollingChargeStatus()
com....ment$3$1 | AmazonPayFragment.java  line  376 in com.common.checkout.payment.amazonpay.AmazonPayFragment$3$1.run()
android.....Handler |  


```
Yes I am using this SDKin India

**Comment by achintsetia** [comment]
Hi @suyashtravel, If you want to onboard your app on Amazon India marketplace, please get in touch with India Payments team. Particularly: parshwas@amazon.com

**Comment by bjguillot** [comment]
Closing this issue as contact information for Amazon Pay India was given above.
